### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by antoniusz** [ebrelsford/qgis-projestions#7]
Plugin version: 0.4.1, on Debian Stretch, Qgis: 3.0.0-Girona, code version 6ebc643

2018O-03-05T22:27:48	WARNING	Warning : Failed to get projestions from API. Please try again and see the error log for details.
2018-03-05T22:27:48	WARNING	TypeError while loading projections
2018-03-05T22:27:48	WARNING	Traceback (most recent call last):
			  File "/home/toni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Projestions/projestions.py", line 147, in run
			    projestions = projestions_api.get_projestions(geojson)
			  File "/home/toni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Projestions/projestions_api.py", line 13, in get_projestions
			    return json.load(urlopen(request))
			  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
			    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
			  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
			    s.__class__.__name__))
			TypeError: the JSON object must be str, not 'bytes'

**Comment by ebrelsford** [comment]
Thanks for the heads-up, the API was temporarily down and is back now, so the plugin should work fine now.

**Comment by antoniusz** [comment]
It's working on qgis 2.18, but not on 3.0.

**Comment by ebrelsford** [comment]
@antoniusz Thanks, I think I see the error now. There will be a new version in the Plugins repository (0.4.2) soon, please try that when you can!

**Comment by antoniusz** [comment]
Thank you. It's ok.

**Comment by ebrelsford** [comment]
@antoniusz `0.4.2` is now in the plugins repo, so if you update Projestions it should now work, please do let me know if it doesn't. I appreciate it!
